server:
  port: 8881

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show sql : true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
